### PR TITLE
Updated infra script guide

### PR DESCRIPTION
**Pull request by JustinaPetr**
# [Adoption k8s infra script] - #ADOPT-1199

## Description

This is an updated version of Ben's work: https://github.com/ceramicstudio/js-composedb/pull/115 
I opened a new PR because there were quite a few cosmetic changes that I added, also slightly edited the original guide.

### CODE REVIEW

**Comment by PaulLeCam** [comment]
I went through the Kubernetes setup on Digital Ocean, here are my notes:

## Specific issues/questions

### Creating a Kubernetes Cluster

> When it comes to choosing your cluster capacity, we recommend starting with the smallest cluster size and upgrading later. For example, to follow this guide you can start with a 1GB RAM and 1vCPU cluster.

Is there anything smaller than Basic - 2vCPU 4 GB RAM available on Digital Ocean?

### Access the ComposeDB API

Could be useful to separate commands from outputs so they can directly copied, ex:

```sh
kubectl port-forward --namespace ceramic composedb-0 7007:7007

Forwarding from 127.0.0.1:7007 -> 7007
Forwarding from [::1]:7007 -> 7007
```

Could instead be:

Command

```sh
kubectl port-forward --namespace ceramic composedb-0 7007:7007
```

Expected output

```sh
Forwarding from 127.0.0.1:7007 -> 7007
Forwarding from [::1]:7007 -> 7007
```

### What is my admin DID?

Why is the admin DID seed encoded in base 64 where we use base 16 in the CLIs please?

Also, I couldn't get access to the seed when running `kubectl get secrets  ceramic-admin -o yaml`, I got the following error: `Error from server (NotFound): secrets "ceramic-admin" not found`.

Running `kubectl get secrets` gives `No resources found in default namespace.`, though I checked I ran `./k8s/base/composedb/create-secrets.sh` in a previous step, and trying to run it again outputs:

```sh
error: failed to create secret secrets "postgres-auth" already exists
error: failed to create secret secrets "ceramic-admin" already exists
```

Any idea what I missed please?

## Overall feedback

The tutorial worked well for deploying to Digital Ocean up to the point of calling the healthcheck API, but then I couldn't access my admin DID.
Overall the tutorial is very clear, the most confusing thing I ran into is the switch between local/generic sections and Digital Ocean specific ones, notably reaching `kubectl port-forward --namespace ceramic composedb-0 7007:7007` that is the local command. Maybe the Digital Ocean steps could be more linear/separated from the generic ones?

**Comment by JustinaPetr** [comment]
Thank you for great feedback @PaulLeCam. I made some cosmetic updates following your recommendation to separate commands and the outputs and added a few clarifications to make sure people can follow the steps easily.

Regarding the `kubectl get secrets` error, looks like that command needed a namespace specification. Just added it there. 

Will think about how we can separate the DO specific commands and local commands more.

**Comment by JustinaPetr** [comment]
@3avi Can I get a review here? If it looks good, we could potentially merge it so that we can go ahead with testing.

**Review by 3avi — APPROVED** [review]
lgtm

**Pull request merged**
